name: CI
env:
  DEBUG: electron-installer-windows

on:
  push:
    branches: [ master ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'windows-latest']
        node-version: [12, 14, 16]

    steps:
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update
          sudo apt-get install wine-stable
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - name: Get source code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install --engine-strict
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
